.github/workflows/CI.yml, Dockerfile
- Dockerfile 작성 및 CI 로직 작성
- 2023/09/20
- Docker 방식으로 배포할 계획이므로 Dockerfile 작성했습니다.
- 추후 CD 로직 작성 예정입니다.
- x
=> [FEATURE-01] Dockerfile 작성 및 CI 로직 작성

.github/ISSUE_TEMPLATE/issue_template.md, src/main/java/com/example/betteriter/config/MainConfig.java, src/main/java/com/example/betteriter/controller/MainController.java, src/main/java/com/example/betteriter/domain/entity/MainEntity.java, src/main/java/com/example/betteriter/domain/repository/MainRepository.java, src/main/java/com/example/betteriter/exception/MainException.java, src/main/java/com/example/betteriter/service/MainService.java
- 커스텀 이슈 템플릿 작성 및 기본 패키지 구조 구현
- 2023/09/20
- 이슈 생성을 위한 커스텀 이슈 템플릿 작성했습니다.
- `계층형 구조` 을 참고해서 기본 패키지 구조 구현했습니다. 
- https://ksh-coding.tistory.com/96
=> [FEATURE-02] 커스텀 이슈 템플릿 작성 및 기본 패키지 구조 구현

src/main/resources/application.yml
- Kakao Oauth 2.0 기본 세팅
- 2023/09/20
- Kakao Developer `Better-Iter` 애플리케이션 생성했습니다.
- application.yml 에 oauth 관련 설정 구현했습니다.
- [Better-Iter 애플리케이션](https://developers.kakao.com/console/app/972094)
- close #3
=> [FEATURE-03] Kakao Oauth 2.0 기본 세팅

src/main/java/com/example/betteriter/config/MainConfig.java, src/main/java/com/example/betteriter/controller/MainController.java, src/main/java/com/example/betteriter/domain/entity/MainEntity.java, src/main/java/com/example/betteriter/domain/repository/MainRepository.java, src/main/java/com/example/betteriter/exception/MainException.java, src/main/java/com/example/betteriter/global/common/entity/BaseEntity.java, src/main/java/com/example/betteriter/global/common/response/BaseResponse.java, src/main/java/com/example/betteriter/global/config/MainConfig.java, src/main/java/com/example/betteriter/global/error/ErrorResponse.java, src/main/java/com/example/betteriter/global/error/GloblaExceptionHandler.java, src/main/java/com/example/betteriter/infra/Email.java, src/main/java/com/example/betteriter/main/controller/MainController.java, src/main/java/com/example/betteriter/main/dao/MainDao.java, src/main/java/com/example/betteriter/main/domain/entity/MainEntity.java, src/main/java/com/example/betteriter/main/domain/repository/MainRepository.java, src/main/java/com/example/betteriter/main/dto/MainDto.java, src/main/java/com/example/betteriter/main/exception/MainException.java, src/main/java/com/example/betteriter/main/service/MainService.java, src/main/java/com/example/betteriter/service/MainService.java
- domain 디렉토리 구조 적용
- 09.21
- 계층형 디렉토리 구조에서 도메인 구조로 변경
- 변경 결과
```
└── src
├── main
│   ├── java
│   │   └── com
│   │       └── example
│   │           └── betteriter
│   │               ├── BetterIterApplication.java
│   │               ├── domain
│   │               │   ├── main
│   │               │   │   ├── service
│   │               │   │   ├── controller
│   │               │   │   ├── dao
│   │               │   │   ├── domain
│   │               │   │   │   ├── entitiy
│   │               │   │   │   └── repository
│   │               │   │   ├── dto
│   │               │   │   └── exception
│   │               │   └── model
│   │               │       ├── Address.java
│   │               │       ├── Email.java
│   │               │       └── Name.java
│   │               ├── …
```
=> domain 디렉토리 구조 적용

src/main/java/com/example/betteriter/example/controller/TempController.java, src/main/java/com/example/betteriter/example/domain/Temp.java, src/main/java/com/example/betteriter/example/dto/TempConverter.java, src/main/java/com/example/betteriter/example/dto/TempResponse.java, src/main/java/com/example/betteriter/example/exception/TempHandler.java, src/main/java/com/example/betteriter/example/repository/TempRepository.java, src/main/java/com/example/betteriter/example/service/TempCommandService.java, src/main/java/com/example/betteriter/example/service/TempCommandServiceImpl.java, src/main/java/com/example/betteriter/example/service/TempQueryService.java, src/main/java/com/example/betteriter/example/service/TempQueryServiceImpl.java, src/main/java/com/example/betteriter/global/common/response/BaseResponse.java, src/main/java/com/example/betteriter/global/common/response/ResponseDto.java, src/main/java/com/example/betteriter/global/error/GlobalExceptionHandler.java, src/main/java/com/example/betteriter/global/error/exception/ErrorCode.java, src/main/java/com/example/betteriter/global/error/exception/GeneralException.java
- Exception 핸들러 구현
- 2023-09-26
-  글로벌 예외 핸들러 생성하기
- 4xx 에러
- 5xx 에러
- 커스텀 exception 클래스 정의하기
- 커스텀 에러 코드 값 정의하기
- 공통 응답 폼 정의
- 성공 응답 정의
- 예외 응답 정의
- 데이터 유효성 응답 정의
- 작동 테스트
- GloblaException 테스트용 템플릿 코드 작성
- 커스텀 Exception 테스트용 템플릿 코드 작성
- ErrorCode 작성 방식 문서화
- 없음
- close #7
=> [FEATURE-7] Exception 핸들러 구현

src/main/java/com/example/betteriter/global/config/properties/JwtProperties.java, src/main/java/com/example/betteriter/global/config/security/SecurityConfig.java, src/main/java/com/example/betteriter/global/config/security/UserAuthentication.java, src/main/java/com/example/betteriter/global/config/web/RedisConfig.java, src/main/java/com/example/betteriter/global/config/web/WebConfig.java, src/main/java/com/example/betteriter/global/filter/JwtAuthenticationEntryPoint.java, src/main/java/com/example/betteriter/global/filter/JwtAuthenticationFilter.java, src/main/java/com/example/betteriter/global/util/JwtUtil.java, src/main/java/com/example/betteriter/global/util/RedisUtil.java, src/main/java/com/example/betteriter/user/controller/KakaoOauthController.java, src/main/java/com/example/betteriter/user/exception/ErrorMessage.java, src/main/java/com/example/betteriter/user/exception/MainException.java, src/main/java/com/example/betteriter/user/exception/UnauthorizedUserException.java, src/main/java/com/example/betteriter/user/service/KakaoOauthService.java, src/main/resources/application.yml
- Jwt 관련 인증/인가 시스템 구축 및 기존 코드 리팩토링, Redis 관련 설정
- 2023/09/27
- `JwtAuthenticationFilter` 구현
- `JwtAuthenticationEntryPoint` 구현
- 401 (Unauthorized) 인 경우(=인증 실패) 동작하는 Exception Handler
- 403(Forbidden) 을 처리하는 Exception Handler 인 `JwtAccessDeniedHandler` 구현 예정입니다. 
- Redis 관련 설정 구현
- [[[Spring Boot] Spring Security 인증, 인가 실패 처리 - authenticationEntryPoint, accessDeniedHandler](https://chb2005.tistory.com/177)](https://chb2005.tistory.com/177)
- [Spring Security + JWT로 Token기반 Security Login 구현하기](https://sup2is.github.io/2020/03/05/spring-security-login-with-jwt.html)
- close #13
=> [FEATURE-13] JwtAuthenticationFilter 을 통한 인증/인가 시스템 구축 및 Redis 관련 설정

src/main/java/com/example/betteriter/example/domain/Temp.java, src/main/java/com/example/betteriter/example/dto/TempConverter.java, src/main/java/com/example/betteriter/example/service/TempQueryServiceImpl.java, src/main/java/com/example/betteriter/global/common/response/ResponseDto.java, src/main/java/com/example/betteriter/global/error/GlobalExceptionHandler.java
- FIX : Temp 및 Exception 코드 수정
- 2023.09.28
- Temp 수정
- GlobalExceptionHandler 수정 
-
- close #
=> [FEATURE-17] FIX : Temp 및 Exception 코드 수정

build.gradle, src/test/java/com/example/betteriter/BetterIterApplicationTests.java, src/test/java/com/example/betteriter/example/controller/TempControllerTest.java
- Test 환경 구축
- 2023/09/28
- `build.grandel` 의존성 추가
- junit-jupiter
- mockito-core
- mockito-junit-jupiter
- junit-platform-runner
- junit-vintage-engine
- `TempControllerTest` 작성
- 유닛 테스트 작동 여부 확인
- 통합 테스트 작동 여부 확인
- 비고: `SecurityConfig`의 필터 체인 설정을 아래의 설정으로 수정한 기준으로 테스트 작성
```java
@Bean
public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
http
.cors()
.and()
.csrf().disable()
.authorizeRequests()
.antMatchers("/login/callback/**", "/temp/**") // 해당 줄 수정
.permitAll()
.anyRequest().authenticated()
.and()
.sessionManagement()
.sessionCreationPolicy(SessionCreationPolicy.STATELESS);
return http.build();
}
```
[ Base ]
- [SwaggerUI + Spring REST Docs 함께 사용하기(feat. Rest Assured)](https://jwkim96.tistory.com/274)
- [Spring …
=> [FEATURE-17]  Test 환경 구축

src/main/java/com/example/betteriter/global/config/security/SecurityConfig.java, src/main/java/com/example/betteriter/global/filter/JwtAccessDeniedHandler.java, src/main/java/com/example/betteriter/global/filter/JwtAuthenticationEntryPoint.java, src/main/java/com/example/betteriter/global/filter/JwtAuthenticationFilter.java, src/main/java/com/example/betteriter/global/util/JwtUtil.java, src/main/java/com/example/betteriter/global/util/SecurityUtil.java, src/main/java/com/example/betteriter/infra/EmailAuthenticationDto.java, src/main/java/com/example/betteriter/infra/EmailService.java, src/main/java/com/example/betteriter/user/controller/AuthController.java, src/main/java/com/example/betteriter/user/controller/KakaoOauthController.java, src/main/java/com/example/betteriter/user/controller/UserController.java, src/main/java/com/example/betteriter/user/domain/User.java, src/main/java/com/example/betteriter/user/dto/JoinDto.java, src/main/java/com/example/betteriter/user/dto/UserServiceTokenResponseDto.java, src/main/java/com/example/betteriter/user/dto/oauth/KakaoJoinDto.java, src/main/java/com/example/betteriter/user/repository/UserRepository.java, src/main/java/com/example/betteriter/user/service/AuthService.java, src/main/java/com/example/betteriter/user/service/KakaoOauthService.java, src/main/java/com/example/betteriter/user/service/UserService.java
- 부족했던 API(닉네임 중복 여부 API, kakao 회원가입 API ) 추가 구현 및 전체 리팩토링  및 테스트 작업
- 2023/10/04
- 닉네임 중복 여부 API 구현
- kakao 회원가입 API 구현
- `JwtAccessDeniedHandler` 구현 -> 인가(403) 에러 처리 핸들러
- `JwtAuthenticationFilter` 코드 리팩토링
- 인증/회원 부분 전체 리팩토링 및 테스트 진행
- 인증 Email 형식 변경 및 테스트
- x
- close #23
=> [FEATURE-23] 인증/회원 부분 API 추가 구현 및 전체 리팩토링 & 테스트

src/main/java/com/example/betteriter/global/config/security/SecurityConfig.java, src/main/java/com/example/betteriter/global/config/web/CorsConfig.java
- CORS 문제 해결
- 2023/10/06
- CorsConfig 파일 생성
- SecurityConfig에 CORS 필터 적용
- https://velog.io/@minnseong/CORS-with-Spring-MVC-Security
- close #15
=> [FEATTURE-15] CORS 문제 해결

.github/workflows/CI.yml, .github/workflows/CICD.yml, .github/workflows/CI_CD.yml, src/main/java/com/example/betteriter/global/filter/JwtAccessDeniedHandler.java, src/main/java/com/example/betteriter/global/filter/JwtAuthenticationFilter.java, src/main/java/com/example/betteriter/user/controller/KakaoOauthController.java
- CI/CD 구축
- 2023/10/05
- 기존 CI.yml 수정 및 보완
- CD 구축
- x
- close #25
=> [FEATURE-25] 기존 CI 수정 및 CD 구축 

.github/workflows/CI_CD.yml, src/main/java/com/example/betteriter/global/config/security/SecurityConfig.java, src/main/java/com/example/betteriter/user/controller/AuthController.java, src/main/java/com/example/betteriter/user/controller/TestController.java, src/main/resources/application.yml
- 일반 로그인 기능 구현 마무리 및 CD 구현 마무리 + 테스트
- 2023/10/09
- 기존 로그인 api `auth/login` 기능 구현 완료
- CD yml 추가 구현 및 테스트 EC2 server 에서 테스트 진행
- [모비딕과 GitHub Actions](https://velog.io/@leejihoon0312/Docker%EC%99%80-GitHub-Actions)
- [Github Actions과 Docker을 활용한 CI/CD 구축](https://velog.io/@leeeeeyeon/Github-Actions%EA%B3%BC-Docker%EC%9D%84-%ED%99%9C%EC%9A%A9%ED%95%9C-CICD-%EA%B5%AC%EC%B6%95)
- close #27
=> [FEATURE-27] 기존 일반 로그인 기능 구현 완료 및 CD 추가 구현 테스트

src/main/java/com/example/betteriter/fo_domain/follow/controller/FollowController.java, src/main/java/com/example/betteriter/fo_domain/follow/domain/Follow.java, src/main/java/com/example/betteriter/fo_domain/follow/dto/FollowResponse.java, src/main/java/com/example/betteriter/fo_domain/follow/exception/FollowHandler.java, src/main/java/com/example/betteriter/fo_domain/follow/repository/FollowRepository.java
- FOLLOW entity 구현
- 2023/10/19
- Follow 도메인 구현
- x
- close #37
=> [FEATURE-37] FOLLOW entity 구현

src/main/java/com/example/betteriter/bo_domain/category/controller/CategoryController.java, src/main/java/com/example/betteriter/bo_domain/category/domain/Category.java, src/main/java/com/example/betteriter/bo_domain/category/dto/CategoryResponse.java, src/main/java/com/example/betteriter/bo_domain/category/exception/CategoryHandler.java, src/main/java/com/example/betteriter/bo_domain/category/repository/CategoryRepository.java
- CATEGORY entity 구현
- 2023/10/19
- CATEGORY domain 구현
- x
- close #32
=> [FEATURE-32] CATEGORY entity 구현

src/main/java/com/example/betteriter/bo_domain/spec/controller/SpecController.java, src/main/java/com/example/betteriter/bo_domain/spec/domain/Spec.java, src/main/java/com/example/betteriter/bo_domain/spec/domain/SpecData.java, src/main/java/com/example/betteriter/bo_domain/spec/dto/SpecResponse.java, src/main/java/com/example/betteriter/bo_domain/spec/exception/SpecHandler.java, src/main/java/com/example/betteriter/bo_domain/spec/repository/SpecRepository.java
- SPEC entity 구현
- 2023/10/20
- Spec
- SpecData
- SpecController
- SpecResponse
- SpecHandler
- SpecRepository
- x
- close #39
=> [FEATURE-39] SPEC entity 구현

src/main/java/com/example/betteriter/fo_domain/review/controller/ReviewController.java, src/main/java/com/example/betteriter/fo_domain/review/domain/Review.java, src/main/java/com/example/betteriter/fo_domain/review/domain/ReviewIamge.java, src/main/java/com/example/betteriter/fo_domain/review/domain/ReviewLike.java, src/main/java/com/example/betteriter/fo_domain/review/domain/ReviewScrap.java, src/main/java/com/example/betteriter/fo_domain/review/domain/ReviewSpec.java, src/main/java/com/example/betteriter/fo_domain/review/dto/ReviewResponse.java, src/main/java/com/example/betteriter/fo_domain/review/exception/ReviewHandler.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewRepository.java
- REVIEW entity 구현
- 2023/10/21
- Review
- ReviewImage
- ReviewLike
- ReviewScrap
- ReviewSpec
- ReviewController
- ReviewResponse
- ReviewHandler
- ReviewRepository
- x
- close #33
=> [FEATURE-33] REVIEW entity 구현

src/main/java/com/example/betteriter/bo_domain/quiz/controller/QuizController.java, src/main/java/com/example/betteriter/bo_domain/quiz/domain/Quiz.java, src/main/java/com/example/betteriter/bo_domain/quiz/domain/QuizAnswer.java, src/main/java/com/example/betteriter/bo_domain/quiz/domain/QuizType.java, src/main/java/com/example/betteriter/bo_domain/quiz/dto/QuizResponse.java, src/main/java/com/example/betteriter/bo_domain/quiz/exception/QuizHandler.java, src/main/java/com/example/betteriter/bo_domain/quiz/repository/QuizRepository.java
- QUIZ entity 구현
- 2023/10/21
- Quiz
- QuizAnswer
- QuizType
- QuizController
- QuizResponse
- QuizHandler
- QuizRepository
- x
- close #38
=> [FEATURE-38] QUIZ entity 구현

src/main/java/com/example/betteriter/fo_domain/search/controller/SearchController.java, src/main/java/com/example/betteriter/fo_domain/search/domain/SearchWord.java, src/main/java/com/example/betteriter/fo_domain/search/dto/SearchWordResponse.java, src/main/java/com/example/betteriter/fo_domain/search/exception/SearchHandler.java, src/main/java/com/example/betteriter/fo_domain/search/repository/SearchRepository.java
- SEARCH entity 구현
- 2023/10/24
- SearchWord
- SearchController
- SearchResponse
- SearchHandler
- SearchWordRepository
- x
- close #44
=> [FEATURE-44] SEARCH entity 구현

src/main/java/com/example/betteriter/bo_domain/news/controller/NewsController.java, src/main/java/com/example/betteriter/bo_domain/news/domain/News.java, src/main/java/com/example/betteriter/bo_domain/news/dto/NewsResponse.java, src/main/java/com/example/betteriter/bo_domain/news/exception/NewsHandler.java, src/main/java/com/example/betteriter/bo_domain/news/repository/NewsRepository.java
- NEWS entity 구현
- 2023/10/24
- News
- NewsController
- NewsResponse
- NewsHandler
- NewsRepository
- x
- close #45
=> [FEATURE-45] NEWS entity 구현

src/main/java/com/example/betteriter/fo_domain/comment/controller/CommentController.java, src/main/java/com/example/betteriter/fo_domain/comment/domain/Comment.java, src/main/java/com/example/betteriter/fo_domain/comment/domain/CommentLike.java, src/main/java/com/example/betteriter/fo_domain/comment/dto/CommentResponse.java, src/main/java/com/example/betteriter/fo_domain/comment/exception/CommentHandler.java, src/main/java/com/example/betteriter/fo_domain/comment/repository/CommentRepository.java, src/main/java/com/example/betteriter/fo_domain/review/domain/ReviewIamge.java
- COMMENT entity 구현
- 2023/10/25
- COMMENT 도메인 구축
- 예약어 관련 문제 해결
- x
- close #59
=> [FEATURE-59] COMMENT entity 구현

src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewRepository.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/main/java/com/example/betteriter/fo_domain/user/controller/AuthController.java, src/main/java/com/example/betteriter/fo_domain/user/domain/User.java, src/main/java/com/example/betteriter/fo_domain/user/service/AuthService.java, src/main/java/com/example/betteriter/global/error/exception/ErrorCode.java
- 기존 홈 화면 조회 API 리팩토링 및 응답으로 반환되는 ErrorCode 구체화
- 2023/11/13
- 홈 화면 조회 API `좋아요 + 스크랩 수` 가장 많은 7개 조회 쿼리 JPQL 로 변경
- 회원 & 인증 부분 ErrorCode 구체화
- x
- close #74
=> [FEATURE-74] 홈 화면 조회 API 및 ErrorCode 구체화

src/main/java/com/example/betteriter/fo_domain/search/controller/SearchController.java, src/main/java/com/example/betteriter/fo_domain/search/dto/SearchLogRedis.java, src/main/java/com/example/betteriter/fo_domain/search/dto/SearchWordResponse.java, src/main/java/com/example/betteriter/fo_domain/search/service/SearchService.java, src/main/java/com/example/betteriter/global/config/web/RedisConfig.java
- 검색 기능 중 유저의 최근 검색어 조회,등록 API 구현
- 2023/11/15
- `RedisConfig` 에 RedisTemplate 추가
- 최근 검색어 조회,등록 API 구현 및 테스팅
- x
- close #79
=> [FEATURE-79] 최근 검색어 조회,등록 API 구현

src/main/java/com/example/betteriter/fo_domain/user/service/AuthService.java, src/main/java/com/example/betteriter/fo_domain/user/service/KakaoOauthService.java, src/main/java/com/example/betteriter/global/util/JwtUtil.java
- api 연동  중 발생한 카카오 oauth 로그인 관련 오류 수정 및 로직 리팩토링
- 2023/11/23
- redis 관련 유효기간 설정
- kakao oauth 로그인 및 일반 로그인 로직 리팩토링
- 테스트
- x
- close #87
=> [FEATURE-87] 카카오 oauth 로그인 관련 오류 수정  및 리팩토링

src/main/java/com/example/betteriter/bo_domain/example/controller/TempController.java, src/main/java/com/example/betteriter/bo_domain/menufacturer/service/ManufacturerService.java, src/main/java/com/example/betteriter/bo_domain/news/controller/NewsController.java, src/main/java/com/example/betteriter/bo_domain/news/service/NewsService.java, src/main/java/com/example/betteriter/fo_domain/comment/controller/CommentController.java, src/main/java/com/example/betteriter/fo_domain/comment/dto/CommentRequest.java, src/main/java/com/example/betteriter/fo_domain/review/controller/ReviewController.java, src/main/java/com/example/betteriter/fo_domain/search/controller/SearchController.java, src/main/java/com/example/betteriter/fo_domain/user/controller/AuthController.java, src/main/java/com/example/betteriter/fo_domain/user/controller/KakaoOauthController.java, src/main/java/com/example/betteriter/fo_domain/user/controller/UserController.java, src/main/java/com/example/betteriter/fo_domain/user/service/AuthService.java, src/main/java/com/example/betteriter/fo_domain/user/service/UserService.java, src/main/java/com/example/betteriter/global/common/code/BaseCode.java, src/main/java/com/example/betteriter/global/common/code/BaseErrorCode.java, src/main/java/com/example/betteriter/global/common/code/status/ErrorStatus.java, src/main/java/com/example/betteriter/global/common/code/status/SuccesStatus.java, src/main/java/com/example/betteriter/global/common/exception/ExceptionAdvice.java, src/main/java/com/example/betteriter/global/common/exception/GeneralException.java, src/main/java/com/example/betteriter/global/common/response/ResponseDto.java, src/main/java/com/example/betteriter/global/filter/JwtAuthenticationEntryPoint.java
- Comment Swagger 명세 추가
- 2023/11/25
- comment swagger 명세 추가
- error status style 형식 맞춤
- x
- close #92
=> [FEATURE/92] Comment Swagger 명세 추가

docker/docker-compose.yml, src/main/java/com/example/betteriter/bo_domain/category/controller/CategoryController.java, src/main/java/com/example/betteriter/bo_domain/category/dto/GetCategoriesResponseDto.java, src/main/java/com/example/betteriter/bo_domain/category/service/CategoryService.java, src/main/java/com/example/betteriter/bo_domain/home/dto/CategoryResponseDto.java, src/main/java/com/example/betteriter/bo_domain/menufacturer/controller/ManufacturerController.java, src/main/java/com/example/betteriter/bo_domain/menufacturer/domain/Manufacturer.java, src/main/java/com/example/betteriter/bo_domain/spec/domain/Spec.java, src/main/java/com/example/betteriter/bo_domain/spec/repository/SpecDataRepository.java, src/main/java/com/example/betteriter/bo_domain/spec/repository/SpecRepository.java, src/main/java/com/example/betteriter/bo_domain/spec/service/SpecService.java, src/main/java/com/example/betteriter/fo_domain/comment/dto/CommentResponse.java, src/main/java/com/example/betteriter/fo_domain/review/controller/ReviewController.java, src/main/java/com/example/betteriter/fo_domain/review/domain/Review.java, src/main/java/com/example/betteriter/fo_domain/review/domain/ReviewImage.java, src/main/java/com/example/betteriter/fo_domain/review/domain/ReviewSpecData.java, src/main/java/com/example/betteriter/fo_domain/review/dto/CreateReviewRequestDto.java, src/main/java/com/example/betteriter/fo_domain/review/dto/GetReviewSpecResponseDto.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewSpecDataRepository.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/main/java/com/example/betteriter/global/constant/Category.java, src/test/java/com/example/betteriter/bo_domain/spec/repository/SpecRepositoryTest.java, src/test/java/com/example/betteriter/bo_domain/spec/service/SpecServiceTest.java, src/test/java/com/example/betteriter/fo_domain/review/service/ReviewServiceTest.java, src/test/java/com/example/betteriter/global/DeserializerTest.java, src/test/resources/application.yml
- 기존 리뷰 등록 API 리팩토링 및 리뷰 등록시 필요한 추가적인  API 구현합니다.
- 2023/11/30
- 리뷰 등록 API 리팩토링 및 테스트 코드 작성
- 카테고리 조회 API 구현
- SpecData 조회 API 구현
- 테스트 코드 작성 및 검증
- x
- close #101
=> [FEATURE-101] 리뷰 등록 API 리팩토링 및 SpecData 조회 API + 카테고리 조회 API 구현

src/main/java/com/example/betteriter/fo_domain/review/controller/ReviewController.java, src/main/java/com/example/betteriter/fo_domain/review/domain/Review.java, src/main/java/com/example/betteriter/fo_domain/review/domain/ReviewLike.java, src/main/java/com/example/betteriter/fo_domain/review/dto/GetCategoryReviewResponseDto.java, src/main/java/com/example/betteriter/fo_domain/review/dto/GetReviewResponseDto.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewRepository.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/main/java/com/example/betteriter/fo_domain/user/domain/UsersDetail.java, src/test/java/com/example/betteriter/fo_domain/review/repository/ReviewRepositoryTest.java, src/test/java/com/example/betteriter/fo_domain/review/service/ReviewServiceTest.java, src/test/resources/application.yml
- 카테고리 별 리뷰 조회 API 을 구현합니다.
- 2023/12/04
- 카테고리 별 리뷰 조회 서비스,레포지토리 단위 테스트
- 카테고리 별 리뷰 조회 API 구현
- 테스트
- x
- close #108
=> [FEATURE-108] 카테고리 별 리뷰 조회 API

src/main/java/com/example/betteriter/fo_domain/review/controller/ReviewController.java, src/main/java/com/example/betteriter/fo_domain/review/domain/Review.java, src/main/java/com/example/betteriter/fo_domain/review/dto/GetReviewResponseDto.java, src/main/java/com/example/betteriter/fo_domain/review/dto/ReviewResponse.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewRepository.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/main/java/com/example/betteriter/global/constant/Category.java, src/test/java/com/example/betteriter/fo_domain/review/service/ReviewServiceTest.java
- 조회 관련 코드를 리팩토링 및 sql 쿼리를 최적화하고 상품명으로 리뷰 검색 API 을 구현합니다.
- 2023/12/06
- sql 쿼리 최적화
- 상품명으로 리뷰 검색 API 구현
- Category image Url 추가
- 테스트
- x
- close #110
=> 리뷰 조회 API 쿼리 최적화 및 상품명으로 리뷰 검색 API 구현

src/main/java/com/example/betteriter/fo_domain/mypage/controller/MypageController.java, src/main/java/com/example/betteriter/fo_domain/mypage/converter/MypageResponseConverter.java, src/main/java/com/example/betteriter/fo_domain/mypage/dto/MypageRequest.java, src/main/java/com/example/betteriter/fo_domain/mypage/dto/MypageResponse.java, src/main/java/com/example/betteriter/fo_domain/mypage/exception/MypageHandler.java, src/main/java/com/example/betteriter/fo_domain/mypage/service/MypageService.java, src/main/java/com/example/betteriter/fo_domain/review/domain/Review.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewRepository.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/main/java/com/example/betteriter/fo_domain/user/service/UserService.java
- mypage review 관련 api 제작
- 2023/12/18
- target이 작성한 review 리스트 조회 (pageing 처리 안함)
- 내가 scrap 중인 review 리스트 조회 (pageing 처리 안함)
- 내가 like 중인 review 리스트 조회 (pageing 처리 안함)
-
- close #95
=> [Feature/95] mypage review 관련 api 제작

src/main/java/com/example/betteriter/bo_domain/menufacturer/service/ManufacturerService.java, src/main/java/com/example/betteriter/fo_domain/review/domain/Review.java, src/main/java/com/example/betteriter/fo_domain/review/domain/ReviewImage.java, src/main/java/com/example/betteriter/fo_domain/review/dto/CreateReviewRequestDto.java, src/main/java/com/example/betteriter/fo_domain/review/dto/GetReviewResponseDto.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewRepository.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/main/java/com/example/betteriter/global/config/test/TestSecurityConfig.java, src/test/java/com/example/betteriter/fo_domain/review/controller/ReviewControllerTest.java, src/test/java/com/example/betteriter/fo_domain/review/repository/ReviewRepositoryTest.java, src/test/java/com/example/betteriter/fo_domain/review/service/ReviewServiceIntegratedTest.java, src/test/java/com/example/betteriter/fo_domain/review/service/ReviewServiceTest.java, src/test/java/com/example/betteriter/global/DeserializerTest.java
-  기존에 구현한 리뷰 검색 API 테스트를 진행하며 관련 코드 리팩토링을 진행합니다.
- 2023/12/19
- 리뷰 검색 API 테스트 코드 작성
- Review 엔티티 필드 추가(ReviewLikedCount,ReviewScrapedCount)
- RDS 반영
-
- close #113
=> [FEATURE-113] 상품명으로 리뷰 검색 API 테스트 진행 및 관련 코드 리팩토링

src/main/java/com/example/betteriter/fo_domain/review/controller/ReviewController.java, src/main/java/com/example/betteriter/fo_domain/review/domain/Review.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewRepository.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/main/resources/application-datasource.yml, src/test/java/com/example/betteriter/fo_domain/review/controller/ReviewControllerTest.java, src/test/java/com/example/betteriter/fo_domain/review/service/ReviewServiceTest.java
- 리뷰 스크랩 API 을 구현합니다.
- 2023/12/22
- 리뷰 스크랩 API
- 테스트 코드 작성 및 테스트
- x
- close #119
=> [FEATURE-119] 리뷰 스크랩 API 구현

src/main/java/com/example/betteriter/fo_domain/review/dto/GetReviewDetailResponseDto.java, src/main/java/com/example/betteriter/fo_domain/review/dto/ReviewDetailResponse.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/test/java/com/example/betteriter/fo_domain/review/controller/ReviewControllerTest.java, src/test/java/com/example/betteriter/fo_domain/review/service/ReviewServiceTest.java
- 리뷰 상세 조회 API 을 리팩토링합니다.
- 2023/12/22
- 리뷰 상세 조회 응답 `isLike`,`isScrap` 을 추가
- 컨트롤러 단위 테스트 진행
- 테스트
- x
- close #123
=> [FEATURE-123] 리뷰 상세 조회 API 리팩토링

src/main/java/com/example/betteriter/fo_domain/review/controller/ReviewController.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/main/java/com/example/betteriter/global/common/code/status/ErrorStatus.java, src/test/java/com/example/betteriter/fo_domain/review/controller/ReviewControllerTest.java, src/test/java/com/example/betteriter/fo_domain/review/service/ReviewServiceTest.java
- AWS S3 구축 및 리뷰 삭제 API 구현합니다.
- 2023/12/27
- AWS S3 구축
- 리뷰 삭제 API 구현
- 테스트 코드 작성 및 테스트 진행
- x
- close #128
=> [Feature-128] AWS S3 구축  및 리뷰 삭제 API 구현

src/main/java/com/example/betteriter/fo_domain/follow/service/FollowService.java, src/main/java/com/example/betteriter/fo_domain/mypage/controller/MypageController.java, src/main/java/com/example/betteriter/fo_domain/mypage/converter/MypageResponseConverter.java, src/main/java/com/example/betteriter/fo_domain/mypage/dto/MypageResponse.java, src/main/java/com/example/betteriter/fo_domain/mypage/service/MypageService.java
- 마이페이지 profile api 구현
- 2023/12/30
- 마이페이지 user prifle 조회 api
- x
- close #98
=> [Feature/98] 마이페이지 profiel api 구현

src/main/java/com/example/betteriter/fo_domain/follow/controller/FollowController.java, src/main/java/com/example/betteriter/fo_domain/follow/dto/FollowRequest.java, src/main/java/com/example/betteriter/fo_domain/follow/repository/FollowReadRepository.java, src/main/java/com/example/betteriter/fo_domain/follow/service/FollowService.java, src/main/java/com/example/betteriter/fo_domain/mypage/controller/MypageController.java, src/main/java/com/example/betteriter/fo_domain/mypage/converter/MypageResponseConverter.java, src/main/java/com/example/betteriter/fo_domain/mypage/dto/MypageResponse.java, src/main/java/com/example/betteriter/fo_domain/mypage/service/MypageService.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewRepository.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java
- Mypage api 리펙토링
- 2023/12/31
- 타 유저 정보 접근이 가능했던 api 에서 불가능 하도록 변경
- x 
- close #133
=> [Feature/133] Mypage api 리펙토링

src/main/java/com/example/betteriter/fo_domain/mypage/controller/MypageController.java, src/main/java/com/example/betteriter/fo_domain/mypage/converter/MypageResponseConverter.java, src/main/java/com/example/betteriter/fo_domain/mypage/dto/MypageResponse.java, src/main/java/com/example/betteriter/fo_domain/mypage/service/MypageService.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewRepository.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java
- mypage porin 조회 api
- 2023/12/31
- point 조회 api 구현
- x
- close #97
=> [Feature/97] mypage porin 조회 api

src/main/java/com/example/betteriter/fo_domain/comment/converter/CommentConverter.java, src/main/java/com/example/betteriter/fo_domain/comment/domain/Comment.java, src/main/java/com/example/betteriter/fo_domain/comment/repository/CommentReadRepository.java, src/main/java/com/example/betteriter/fo_domain/mypage/service/MypageService.java, src/main/java/com/example/betteriter/fo_domain/review/domain/Review.java, src/main/java/com/example/betteriter/fo_domain/review/dto/GetReviewDetailResponseDto.java, src/main/java/com/example/betteriter/fo_domain/review/dto/ReviewDetailResponse.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/main/java/com/example/betteriter/global/common/entity/BaseEntity.java, src/test/java/com/example/betteriter/fo_domain/review/service/ReviewServiceTest.java
- 리뷰 상세 조회 API 응답 필드 변경 및 추가하고 Comment 엔티티에 대댓글과 관련된 필드를 삭제합니다.
- 2023/01/07
- 리뷰 상세 조회 DTO GetReviewDetailResponseDto 필드 추기
- Comment 엔티티 필드 삭제
- 테스트 코드 작성 및 테스트
- x
- close #139
=> [FEATURE-139] 리뷰 상세 조회 응답 필드 변경 및 Comment 엔티티 필드 삭제

src/main/java/com/example/betteriter/fo_domain/review/domain/Review.java, src/main/java/com/example/betteriter/fo_domain/review/dto/CreateReviewRequestDto.java, src/main/java/com/example/betteriter/fo_domain/review/dto/GetReviewDetailResponseDto.java, src/main/java/com/example/betteriter/fo_domain/review/dto/ReviewDetailResponse.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/test/java/com/example/betteriter/fo_domain/review/controller/ReviewControllerTest.java, src/test/java/com/example/betteriter/fo_domain/review/service/ReviewServiceTest.java
- 리뷰 엔티티 비교 제품 필드 추가 및 로직 추가
- 2024/01/07
- 리뷰 엔티티 comparedProductName 필드 추가
- 이에 따른 로직 변경
-
- close #141
=> [FEATURE-141] 리뷰 엔티티 비교 제품 필드 추가 및 로직 추가

src/main/java/com/example/betteriter/fo_domain/comment/controller/CommentController.java, src/main/java/com/example/betteriter/fo_domain/mypage/controller/MypageController.java, src/main/java/com/example/betteriter/fo_domain/review/controller/ReviewController.java, src/main/java/com/example/betteriter/fo_domain/review/domain/ReviewLike.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewLikeRepository.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewRepository.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/main/java/com/example/betteriter/global/common/code/status/ErrorStatus.java, src/test/java/com/example/betteriter/fo_domain/review/controller/ReviewControllerTest.java, src/test/java/com/example/betteriter/fo_domain/review/service/ReviewServiceTest.java
- 리뷰 좋아요 취소 API 을 구현하고 필요한 코드를 리팩토링합니다.
- 2024/01/08
- 리뷰 좋아요 취소 API 구현
- API 대해 테스트 코드 작성 및 테스트 진행
- 마이페이지,댓글 관련 코드 리팩토링
- x
- close #143
=> [FEATURE-143] 리뷰 좋아요 취소 API 구현 및 마이페이지,댓글 관련 코드 리팩토링

src/main/java/com/example/betteriter/fo_domain/follow/domain/Follow.java, src/main/java/com/example/betteriter/fo_domain/follow/repository/FollowReadRepository.java, src/main/java/com/example/betteriter/fo_domain/follow/service/FollowService.java, src/main/java/com/example/betteriter/fo_domain/mypage/controller/MypageController.java, src/main/java/com/example/betteriter/fo_domain/mypage/converter/MypageResponseConverter.java, src/main/java/com/example/betteriter/fo_domain/mypage/service/MypageService.java
-  Mypage Follow 조회 기능 수정
- 2024/01/.08
- following 목록 조회
- follower 목록 조회
- x
- close #146
=> [FEATURE-146] Mypage Follow 조회 기능 수정

src/main/java/com/example/betteriter/fo_domain/review/controller/ReviewController.java, src/main/java/com/example/betteriter/fo_domain/review/domain/Review.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewLikeRepository.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewScrapRepository.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/main/java/com/example/betteriter/global/common/code/status/ErrorStatus.java, src/test/java/com/example/betteriter/fo_domain/review/controller/ReviewControllerTest.java, src/test/java/com/example/betteriter/fo_domain/review/service/ReviewServiceTest.java
- 리뷰 스크랩 취소 API 구현 및 기존 코드 리팩토링
- 2024/01/08
- 리뷰 스크랩 취소 API
- 리뷰 좋아요,스크랩 관련 리팩토링
- 테스트 코드 작성 및 테스트
- x
- close #145
=> [FEATURE-145] 리뷰 스크랩 취소 API 구현 및 기존 스크랩,좋아요 API 리팩토링 & 테스트 진행

src/main/java/com/example/betteriter/fo_domain/mypage/controller/MypageController.java, src/main/java/com/example/betteriter/fo_domain/mypage/converter/MypageResponseConverter.java, src/main/java/com/example/betteriter/fo_domain/mypage/dto/MypageResponse.java, src/main/java/com/example/betteriter/fo_domain/mypage/service/MypageService.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewRepository.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java
- mypage paging 사용 api 리펙토링
- 2024.01.24
- pageinfo 데이터 추가
-
- close #151
=> [FEATURE/151] mypage paging 사용 api 리펙토링

src/main/java/com/example/betteriter/fo_domain/follow/controller/FollowController.java, src/main/java/com/example/betteriter/fo_domain/follow/converter/FollowResponseConverter.java, src/main/java/com/example/betteriter/fo_domain/follow/dto/FollowRequest.java, src/main/java/com/example/betteriter/fo_domain/follow/dto/FollowResponse.java, src/main/java/com/example/betteriter/fo_domain/follow/service/FollowService.java, src/main/java/com/example/betteriter/global/common/code/status/ErrorStatus.java
- Follow request 값 통일
- 2024.01.24
- follow 기능 수정
- 중복 팔로우 방지
- 자기 팔로우 방지
- unfollow 기능 수정
- request email 입력에서 id로 변경
- x
- close #150
=> [REFACTOR-150] Follow request 값 통일

build.gradle, src/main/java/com/example/betteriter/fo_domain/review/controller/ReviewController.java, src/main/java/com/example/betteriter/fo_domain/review/dto/CreateReviewRequestDto.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/main/java/com/example/betteriter/fo_domain/user/controller/AuthController.java, src/main/java/com/example/betteriter/fo_domain/user/service/AuthService.java, src/main/java/com/example/betteriter/global/common/code/status/ErrorStatus.java, src/main/java/com/example/betteriter/infra/email/EmailAuthenticationDto.java, src/main/java/com/example/betteriter/infra/email/EmailDto.java, src/main/java/com/example/betteriter/infra/email/EmailService.java, src/main/java/com/example/betteriter/infra/s3/ImageUploadService.java, src/main/java/com/example/betteriter/infra/s3/S3Service.java, src/main/resources/application-aws.yml, src/main/resources/application.yml, src/test/java/com/example/betteriter/fo_domain/review/controller/ReviewControllerTest.java, src/test/java/com/example/betteriter/fo_domain/review/service/ReviewServiceTest.java, src/test/java/com/example/betteriter/global/DeserializerTest.java
- s3 기능 추가 및 API 수정
- 2024/02/01
- s3 기능 추가
- 기존 API 수정
- 테스트 코드 수정
- [Springboot로 S3 파일 업로드하기](https://www.sunny-son.space/spring/Springboot%EB%A1%9C%20S3%20%ED%8C%8C%EC%9D%BC%20%EC%97%85%EB%A1%9C%EB%93%9C/)
- close #159
=> [FEATURE-159]

src/main/java/com/example/betteriter/bo_domain/spec/service/SpecConnector.java, src/main/java/com/example/betteriter/bo_domain/spec/service/SpecConnectorImpl.java, src/main/java/com/example/betteriter/fo_domain/review/controller/ReviewController.java, src/main/java/com/example/betteriter/fo_domain/review/domain/Review.java, src/main/java/com/example/betteriter/fo_domain/review/domain/ReviewImage.java, src/main/java/com/example/betteriter/fo_domain/review/domain/ReviewSpecData.java, src/main/java/com/example/betteriter/fo_domain/review/dto/UpdateReviewRequestDto.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewImageRepository.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewSpecDataRepository.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/main/java/com/example/betteriter/global/common/code/status/ErrorStatus.java, src/main/java/com/example/betteriter/infra/s3/ImageUploadService.java, src/main/java/com/example/betteriter/infra/s3/S3Service.java, src/test/java/com/example/betteriter/fo_domain/review/service/ReviewServiceTest.java
- 리뷰 수정 API 구현
- 2024.02.13
- 리뷰 수정 API 구현
- x
- close #130
=> [Feature/130] 리뷰 수정 API 구현

src/main/java/com/example/betteriter/fo_domain/follow/converter/FollowConverter.java
- follow 로직 수정
- 2024.02.14
- follow 로직 수정
- x
- close #166
=> [feature/166]: follow 로직 수정

src/main/java/com/example/betteriter/fo_domain/mypage/controller/MypageController.java, src/main/java/com/example/betteriter/fo_domain/mypage/dto/MypageRequest.java, src/main/java/com/example/betteriter/fo_domain/mypage/service/MypageService.java, src/main/java/com/example/betteriter/fo_domain/user/domain/UsersDetail.java, src/main/java/com/example/betteriter/fo_domain/user/service/UserService.java, src/main/java/com/example/betteriter/infra/s3/ImageUploadService.java, src/main/java/com/example/betteriter/infra/s3/S3Service.java
- 프로필 수정 기능 구현
- 2024.02.20
- 프로필 수정 기능 구현
- x
- close #168
=> [Feature/168] 프로필 수정 기능 구현

src/main/java/com/example/betteriter/fo_domain/mypage/controller/MypageController.java, src/main/java/com/example/betteriter/fo_domain/mypage/dto/MypageRequest.java, src/main/java/com/example/betteriter/fo_domain/mypage/service/MypageService.java
- 카테고리 수정 기능 추가
- 2024.02.25
- 카테고리 수정 기능 구현
- x
- close #170
=> [Feature/170] 카테고리 수정 기능 추가

src/main/java/com/example/betteriter/fo_domain/follow/repository/FollowReadRepository.java, src/main/java/com/example/betteriter/fo_domain/follow/service/FollowService.java
- 언팔로우 문제 해결
- 2024.02.25
- 언팔로우 문제 해결
- x
- close #171
=> [Feature/171] 언팔로우 문제 해결

src/main/java/com/example/betteriter/fo_domain/mypage/controller/MypageController.java, src/main/java/com/example/betteriter/fo_domain/mypage/service/MypageService.java, src/main/java/com/example/betteriter/fo_domain/user/domain/UsersDetail.java, src/main/java/com/example/betteriter/infra/s3/S3Service.java
- 유저 프로필 수정 api null 분기 처리 및 이미지 url 문제 해결
- 2024.02.26
- 프로필 수정 api
- null requset에 대한 분기 처리 구현
- MultipartFile가 empty인 경우에 대한 분기 처리 구현
- S3Service
- imageUrl 생성 책임을 S3Client에게 위임
- x
- close #178
=> [Feature/178] 유저 프로필 수정 api null 분기 처리 및 이미지 url 문제 해결

src/main/java/com/example/betteriter/fo_domain/follow/repository/FollowReadRepository.java, src/main/java/com/example/betteriter/fo_domain/follow/service/FollowService.java
- unfollow 문제 해결
- 2024.02.26
- unfollow 문제 해결
- x
- close #180
=> [Feature/180] unfollow 문제 해결

src/main/java/com/example/betteriter/fo_domain/mypage/converter/MypageResponseConverter.java, src/main/java/com/example/betteriter/fo_domain/mypage/dto/MypageResponse.java, src/main/java/com/example/betteriter/fo_domain/review/repository/ReviewRepository.java
- 마이페이지 포인트 조회 api 반환값 수정
- 2024.02..28
- Mypage point 조회 반환값 수정
- x
- close #182
=> [Feature/182] 마이페이지 포인트 조회 api 반환값 수정

src/main/java/com/example/betteriter/fo_domain/review/dto/GetReviewDetailResponseDto.java
- review 상세 조회 api 반환값 수정
- 2024.02.28
- 반환값에 category 정보 추가
- x
- close #184
=> [feature/184] review 상세 조회 api 반환값 수정

src/main/java/com/example/betteriter/fo_domain/review/controller/ReviewController.java, src/main/java/com/example/betteriter/fo_domain/review/domain/Review.java, src/main/java/com/example/betteriter/fo_domain/review/dto/UpdateReviewRequestDto.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/main/java/com/example/betteriter/global/common/code/status/ErrorStatus.java, src/main/java/com/example/betteriter/infra/s3/ImageUploadService.java, src/main/java/com/example/betteriter/infra/s3/S3Service.java, src/main/resources/application-aws.yml
- 리뷰 삭제 시 s3 접근해서 이미지를 삭제하는 로직 추가합니다.
- 2024/02/29
- s3 이미지 삭제
- 기타 이미지 관련 로직 추가
- s3 Access Denied 에러가 발생해서 access key, secret key 모두 재발급 후 노션에 최신화해놓았습니다.
-  [[AWS] s3 파일 삭제 Access Denied Issue](https://velog.io/@xav/AWS-S3-%ED%8C%8C%EC%9D%BC-%EC%82%AD%EC%A0%9C-Access-Denied-Issue)
- close #162
=> [FEATURE/162] 리뷰 삭제시 s3 이미지 삭제 로직 추가

src/main/java/com/example/betteriter/fo_domain/review/controller/ReviewController.java, src/main/java/com/example/betteriter/fo_domain/review/dto/UpdateReviewRequestDto.java, src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java, src/main/java/com/example/betteriter/infra/s3/ImageUploadService.java, src/main/java/com/example/betteriter/infra/s3/S3Service.java, src/test/java/com/example/betteriter/fo_domain/review/service/ReviewServiceTest.java
- 리뷰 수정 api 이미지 관련 로직 수정
- 2024.02.29
- 임시 image url 발급 api 구현
- review update 후 사용 되지 않는 image url 삭제 로직 추가
- x
- close #186
=> [Feature/186] 리뷰 수정 api 이미지 관련 로직 수정

src/main/java/com/example/betteriter/fo_domain/review/dto/GetReviewDetailResponseDto.java, src/main/java/com/example/betteriter/fo_domain/review/dto/GetSpecDataDto.java, src/main/resources/application-dev.yml
- 리뷰 상세 조회 반환값 수정
- 2024.03.05
- 리뷰 상세 조회 반환 값 수정
- x
- close #191
=> [Feature/191] 리뷰 상세 조회 반환값 수정

src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java
- 리뷰 수정 image 저장 관련 문제 해결
- 2024.03.05
- 임시 문제 해결
- x
- close #193
=> [Feature/193] 리뷰 수정 image 저장 관련 문제 해결

src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java
-  리뷰 수정 api 로직 오류 해결
- 2024.03.06
- reviewSpecData 수정 로직 변경
- x
- close #195
=> [Feature/195] 리뷰 수정 api 로직 오류 해결

src/main/java/com/example/betteriter/fo_domain/review/service/ReviewService.java
-  리뷰 수정 api 로직 오류 해결
- 2024.03.06
- reviewSpecData 수정 로직 변경
- x
- close #195
=> [Feature/195] 리뷰 수정 api 로직 오류 해결 
